version: '3.8'

services:
  trino-lcm:
    build: .
    volumes:
      - .:/app
      - ../explain_analyze_results:/app/explain_analyze_results
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - DGLBACKEND=pytorch
      - NODE02={}
      - NODE03={}
      - NODE04={}
      - NODE05={}
    command: python src/trino_lcm/scripts/test_docker_status.py
